export interface Shopper {
  _id: string; // Wallet address used as unique identifier/primary key
  walletAddress: string; // Same as _id, kept for clarity and queries
  name?: string;
  email?: string;
  createdAt: Date;
  updatedAt: Date;
  totalOrders?: number;
  totalSpent?: number;
}

export interface Product {
  _id?: string;
  merchantWalletAddress?: string; // Optional for backward compatibility
  name: string;
  description: string;
  price: number; // Price in RLUSD
  image: string; // Primary image
  imageUrl?: string; // Alias for image
  images?: string[]; // Additional images
  category?: string;
  stock: number;
  isActive?: boolean; // Optional for backward compatibility
  createdAt?: Date;
  updatedAt?: Date;
}

export interface Sale {
  _id?: string;
  merchantWalletAddress: string;
  productId: string;
  productName: string;
  quantity: number;
  pricePerUnit: number; // Price per unit at time of sale (in XRP)
  totalAmount: number; // Total amount = quantity * pricePerUnit (in XRP)
  currency: string; // Always "XRP"
  customerWalletAddress: string;
  transactionHash: string; // XRPL transaction hash
  status: "pending" | "completed" | "failed";
  createdAt?: Date;
  completedAt?: Date; // When transaction was completed
  failedAt?: Date; // When transaction failed (if applicable)
}

export interface CartItem {
  product: Product;
  quantity: number;
}

export type DeliveryStage =
  | "PENDING"
  | "IN_TRANSIT"
  | "SINGAPORE"
  | "OUT_FOR_DELIVERY"
  | "DELIVERED"
  | "FINISHED"
  | "CANCELLED";

export interface DeliveryConfirmation {
  confirmed: boolean;
  confirmedAt?: Date;
  notDelivered?: boolean;
  autoConfirmed?: boolean;
  autoConfirmedAt?: Date;
}

export interface OrderFeedback {
  rating: number; // 1-5 stars
  comment?: string;
  submittedAt?: Date;
}

export interface DeliveryStatus {
  stage: DeliveryStage | string;
  timestamp: Date;
  location?: string;
  carrier?: string;
}

export interface Order {
  _id?: string;
  userWalletAddress: string;
  items: CartItem[];
  total: number;
  status: "pending" | "completed" | "cancelled";
  transactionHash?: string;
  /**
   * 1-1 relationship with EscrowOracle document
   * Links to EscrowOracle._id in the oracle backend's "escrow-oracle" collection
   * Used to fetch fulfillment secret for EscrowFinish transaction
   */
  oracleDbId?: string;
  createdAt?: Date;
  deliveryTracking?: DeliveryStatus[];
  currentDeliveryStage?: DeliveryStage | string;
  estimatedDeliveryDate?: Date;
  deliveryConfirmation?: DeliveryConfirmation;
  feedback?: OrderFeedback;
}

// Keep User for backward compatibility (type alias)
export type User = Shopper;

/**
 * EscrowOracle represents an escrow document stored in the oracle backend MongoDB
 * Collection: "escrow-oracle"
 *
 * This document is created by the oracle backend when prepare() is called,
 * and updated by the oracle backend listener when EscrowCreate/Finish/Cancel transactions are detected.
 */
export interface EscrowOracle {
  _id?: string; // MongoDB ObjectId (automatically generated)
  condition: string; // Escrow condition hash (required for EscrowCreate, generated by oracle backend)
  fulfillment: string; // Fulfillment secret (required for EscrowFinish, generated by oracle backend)
  buyerAddress: string; // Wallet address of the buyer (who creates the escrow)
  sellerAddress: string; // Wallet address of the seller/merchant (who receives funds)
  amount: string; // Amount in drops (string to avoid precision issues, e.g., "5000000")
  cancelAfter: number; // Ripple time when escrow can be cancelled (unix timestamp in ripple time)
  status: string; // Status: "PREPARED", "CREATED", "FINISHED", "CANCELLED", etc.
  isProcessing: boolean; // Whether the escrow is currently being processed by oracle backend
  isFinalized: boolean; // Whether the escrow has been finalized (FINISHED or CANCELLED)
  retryCount: number; // Number of retry attempts for transaction processing
  txHash?: string; // Transaction hash of EscrowCreate (set by oracle backend listener after transaction is detected on ledger)
  createdAt: Date; // When the escrow was created/prepared in oracle backend
  updatedAt?: Date; // Last update timestamp (managed by MongoDB/Mongoose)
  __v?: number; // MongoDB version key (automatically added by Mongoose, used for optimistic concurrency)
}
